// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: protobuf/messages.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block chain
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash      string                 `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_protobuf_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        uint64                 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_protobuf_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Blocks Topic
type NewBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBlock) Reset() {
	*x = NewBlock{}
	mi := &file_protobuf_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlock) ProtoMessage() {}

func (x *NewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlock.ProtoReflect.Descriptor instead.
func (*NewBlock) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{2}
}

func (x *NewBlock) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type NewTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTransactions) Reset() {
	*x = NewTransactions{}
	mi := &file_protobuf_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTransactions) ProtoMessage() {}

func (x *NewTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTransactions.ProtoReflect.Descriptor instead.
func (*NewTransactions) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{3}
}

func (x *NewTransactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BlocksSubMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BlocksSubMessages_NewBlock
	//	*BlocksSubMessages_NewTransactions
	Payload       isBlocksSubMessages_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksSubMessages) Reset() {
	*x = BlocksSubMessages{}
	mi := &file_protobuf_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksSubMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksSubMessages) ProtoMessage() {}

func (x *BlocksSubMessages) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksSubMessages.ProtoReflect.Descriptor instead.
func (*BlocksSubMessages) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{4}
}

func (x *BlocksSubMessages) GetPayload() isBlocksSubMessages_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlocksSubMessages) GetNewBlock() *NewBlock {
	if x != nil {
		if x, ok := x.Payload.(*BlocksSubMessages_NewBlock); ok {
			return x.NewBlock
		}
	}
	return nil
}

func (x *BlocksSubMessages) GetNewTransactions() *NewTransactions {
	if x != nil {
		if x, ok := x.Payload.(*BlocksSubMessages_NewTransactions); ok {
			return x.NewTransactions
		}
	}
	return nil
}

type isBlocksSubMessages_Payload interface {
	isBlocksSubMessages_Payload()
}

type BlocksSubMessages_NewBlock struct {
	NewBlock *NewBlock `protobuf:"bytes,1,opt,name=new_block,json=newBlock,proto3,oneof"`
}

type BlocksSubMessages_NewTransactions struct {
	NewTransactions *NewTransactions `protobuf:"bytes,2,opt,name=new_transactions,json=newTransactions,proto3,oneof"`
}

func (*BlocksSubMessages_NewBlock) isBlocksSubMessages_Payload() {}

func (*BlocksSubMessages_NewTransactions) isBlocksSubMessages_Payload() {}

// Network messages
type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_protobuf_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Handshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetBlocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHeight    int64                  `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight      int64                  `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	Height        int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocks) Reset() {
	*x = GetBlocks{}
	mi := &file_protobuf_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocks) ProtoMessage() {}

func (x *GetBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocks.ProtoReflect.Descriptor instead.
func (*GetBlocks) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlocks) GetFromHeight() int64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *GetBlocks) GetToHeight() int64 {
	if x != nil {
		return x.ToHeight
	}
	return 0
}

func (x *GetBlocks) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type NetworkMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NetworkMessages_Handshake
	//	*NetworkMessages_HandshakeResponse
	//	*NetworkMessages_GetBlocks
	//	*NetworkMessages_GetBlocksResponse
	Payload       isNetworkMessages_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMessages) Reset() {
	*x = NetworkMessages{}
	mi := &file_protobuf_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMessages) ProtoMessage() {}

func (x *NetworkMessages) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMessages.ProtoReflect.Descriptor instead.
func (*NetworkMessages) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkMessages) GetPayload() isNetworkMessages_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NetworkMessages) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*NetworkMessages_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *NetworkMessages) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*NetworkMessages_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *NetworkMessages) GetGetBlocks() *GetBlocks {
	if x != nil {
		if x, ok := x.Payload.(*NetworkMessages_GetBlocks); ok {
			return x.GetBlocks
		}
	}
	return nil
}

func (x *NetworkMessages) GetGetBlocksResponse() *GetBlocksResponse {
	if x != nil {
		if x, ok := x.Payload.(*NetworkMessages_GetBlocksResponse); ok {
			return x.GetBlocksResponse
		}
	}
	return nil
}

type isNetworkMessages_Payload interface {
	isNetworkMessages_Payload()
}

type NetworkMessages_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type NetworkMessages_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,2,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type NetworkMessages_GetBlocks struct {
	GetBlocks *GetBlocks `protobuf:"bytes,3,opt,name=get_blocks,json=getBlocks,proto3,oneof"`
}

type NetworkMessages_GetBlocksResponse struct {
	GetBlocksResponse *GetBlocksResponse `protobuf:"bytes,4,opt,name=get_blocks_response,json=getBlocksResponse,proto3,oneof"`
}

func (*NetworkMessages_Handshake) isNetworkMessages_Payload() {}

func (*NetworkMessages_HandshakeResponse) isNetworkMessages_Payload() {}

func (*NetworkMessages_GetBlocks) isNetworkMessages_Payload() {}

func (*NetworkMessages_GetBlocksResponse) isNetworkMessages_Payload() {}

// DNS
type DNSHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSHost) Reset() {
	*x = DNSHost{}
	mi := &file_protobuf_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHost) ProtoMessage() {}

func (x *DNSHost) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHost.ProtoReflect.Descriptor instead.
func (*DNSHost) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DNSHost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DNSHost) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSHost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DNSHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dns           *DNSHost               `protobuf:"bytes,1,opt,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSHostResponse) Reset() {
	*x = DNSHostResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHostResponse) ProtoMessage() {}

func (x *DNSHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHostResponse.ProtoReflect.Descriptor instead.
func (*DNSHostResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DNSHostResponse) GetDns() *DNSHost {
	if x != nil {
		return x.Dns
	}
	return nil
}

type DNSSeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seeds         []*DNSHost             `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSSeedsResponse) Reset() {
	*x = DNSSeedsResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSSeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSSeedsResponse) ProtoMessage() {}

func (x *DNSSeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSSeedsResponse.ProtoReflect.Descriptor instead.
func (*DNSSeedsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DNSSeedsResponse) GetSeeds() []*DNSHost {
	if x != nil {
		return x.Seeds
	}
	return nil
}

type DNSNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*DNSHost             `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSNodesResponse) Reset() {
	*x = DNSNodesResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSNodesResponse) ProtoMessage() {}

func (x *DNSNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSNodesResponse.ProtoReflect.Descriptor instead.
func (*DNSNodesResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{13}
}

func (x *DNSNodesResponse) GetNodes() []*DNSHost {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_protobuf_messages_proto protoreflect.FileDescriptor

var file_protobuf_messages_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6e, 0x6f, 0x73, 0x6f, 0x67,
	0x6f, 0x22, 0xc8, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f, 0x72, 0x6f, 0x6f,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x6f, 0x73, 0x6f,
	0x67, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x9f, 0x01, 0x0a,
	0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f,
	0x0a, 0x08, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x6f, 0x73, 0x6f,
	0x67, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22,
	0x4a, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67,
	0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x11,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x2f, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x4e, 0x65,
	0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x44, 0x0a, 0x10, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e,
	0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x25, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x11, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f,
	0x6d, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3a, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x9c, 0x02, 0x0a, 0x0f, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x09,
	0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12,
	0x4a, 0x0a, 0x12, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x6f,
	0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x67,
	0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x48, 0x00, 0x52, 0x09, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12,
	0x4b, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e,
	0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x47, 0x0a, 0x07, 0x44, 0x4e, 0x53, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x34, 0x0a, 0x0f, 0x44, 0x4e, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x44, 0x4e, 0x53, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x03, 0x64, 0x6e, 0x73, 0x22, 0x39, 0x0a, 0x10, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x65,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x65,
	0x65, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x6f, 0x73, 0x6f,
	0x67, 0x6f, 0x2e, 0x44, 0x4e, 0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x73, 0x65, 0x65, 0x64,
	0x73, 0x22, 0x39, 0x0a, 0x10, 0x44, 0x4e, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x6f, 0x73, 0x6f, 0x67, 0x6f, 0x2e, 0x44, 0x4e,
	0x53, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_protobuf_messages_proto_rawDescOnce sync.Once
	file_protobuf_messages_proto_rawDescData []byte
)

func file_protobuf_messages_proto_rawDescGZIP() []byte {
	file_protobuf_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)))
	})
	return file_protobuf_messages_proto_rawDescData
}

var file_protobuf_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protobuf_messages_proto_goTypes = []any{
	(*Block)(nil),             // 0: nosogo.Block
	(*Transaction)(nil),       // 1: nosogo.Transaction
	(*NewBlock)(nil),          // 2: nosogo.NewBlock
	(*NewTransactions)(nil),   // 3: nosogo.NewTransactions
	(*BlocksSubMessages)(nil), // 4: nosogo.BlocksSubMessages
	(*Handshake)(nil),         // 5: nosogo.Handshake
	(*HandshakeResponse)(nil), // 6: nosogo.HandshakeResponse
	(*GetBlocks)(nil),         // 7: nosogo.GetBlocks
	(*GetBlocksResponse)(nil), // 8: nosogo.GetBlocksResponse
	(*NetworkMessages)(nil),   // 9: nosogo.NetworkMessages
	(*DNSHost)(nil),           // 10: nosogo.DNSHost
	(*DNSHostResponse)(nil),   // 11: nosogo.DNSHostResponse
	(*DNSSeedsResponse)(nil),  // 12: nosogo.DNSSeedsResponse
	(*DNSNodesResponse)(nil),  // 13: nosogo.DNSNodesResponse
}
var file_protobuf_messages_proto_depIdxs = []int32{
	1,  // 0: nosogo.Block.transactions:type_name -> nosogo.Transaction
	0,  // 1: nosogo.NewBlock.block:type_name -> nosogo.Block
	1,  // 2: nosogo.NewTransactions.transactions:type_name -> nosogo.Transaction
	2,  // 3: nosogo.BlocksSubMessages.new_block:type_name -> nosogo.NewBlock
	3,  // 4: nosogo.BlocksSubMessages.new_transactions:type_name -> nosogo.NewTransactions
	0,  // 5: nosogo.GetBlocksResponse.blocks:type_name -> nosogo.Block
	5,  // 6: nosogo.NetworkMessages.handshake:type_name -> nosogo.Handshake
	6,  // 7: nosogo.NetworkMessages.handshake_response:type_name -> nosogo.HandshakeResponse
	7,  // 8: nosogo.NetworkMessages.get_blocks:type_name -> nosogo.GetBlocks
	8,  // 9: nosogo.NetworkMessages.get_blocks_response:type_name -> nosogo.GetBlocksResponse
	10, // 10: nosogo.DNSHostResponse.dns:type_name -> nosogo.DNSHost
	10, // 11: nosogo.DNSSeedsResponse.seeds:type_name -> nosogo.DNSHost
	10, // 12: nosogo.DNSNodesResponse.nodes:type_name -> nosogo.DNSHost
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protobuf_messages_proto_init() }
func file_protobuf_messages_proto_init() {
	if File_protobuf_messages_proto != nil {
		return
	}
	file_protobuf_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*BlocksSubMessages_NewBlock)(nil),
		(*BlocksSubMessages_NewTransactions)(nil),
	}
	file_protobuf_messages_proto_msgTypes[9].OneofWrappers = []any{
		(*NetworkMessages_Handshake)(nil),
		(*NetworkMessages_HandshakeResponse)(nil),
		(*NetworkMessages_GetBlocks)(nil),
		(*NetworkMessages_GetBlocksResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_messages_proto_depIdxs,
		MessageInfos:      file_protobuf_messages_proto_msgTypes,
	}.Build()
	File_protobuf_messages_proto = out.File
	file_protobuf_messages_proto_goTypes = nil
	file_protobuf_messages_proto_depIdxs = nil
}
