name: NosoGo

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "LICENSE", "CHANGELOG.md", "cliff.toml" ]

  pull_request:
    branches: [ main ]

jobs:

  test-build:
    name: Test and Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
          os: [ ubuntu-latest, windows-latest, macos-latest]
          go: [ "1.22", "1.23" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Run tests
        run: make test

      - name: Build Node
        run: make nosogod

      - name: Build Client
        run: make nosogocli

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: nosogo-${{ matrix.os }}-go_${{ matrix.go }}
          path: bin/nosogo*

  release:
    if: contains(github.ref_type, 'tag')
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: test-build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Release
        run: make release-all

      - name: Generate Release Notes
        id: git-cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: EIYARO ${{ github.ref_name }}
          body: ${{ steps.git-cliff.outputs.content }}
          files: target/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
